### ISSUE TITLE
SaltPyLint 2017.4.5 does not have Git tag

### ISSUE THREAD

**Issue by vutny** [saltstack/salt-pylint#13]
Hi @s0undt3ch !

The latest and greatest SaltPyLint release `2017.4.5` is available from pypi, but it appears that GitHub release (and appropriate tag) is missing:
https://github.com/saltstack/salt-pylint/releases
https://github.com/saltstack/salt-pylint/tags

This also does not match version info in `saltpylint/version.py`.

**Comment by s0undt3ch** [comment]
I'll try to do another release tonight.

**Comment by s0undt3ch** [comment]
I had forgotten to push tags after release.
Just release a new version with your latest changes and this time I didn't forget to push the tags.
